name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.4.1
author: Ryan Heise <ryan+flutter@ryanheise.com>
homepage: https://github.com/ryanheise/audio_service

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.22.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ryanheise.audioservice
    pluginClass: AudioServicePlugin
